### PR TITLE
Delete .DS_store files

### PR DESCRIPTION
**Pull request by baitun**

### CODE REVIEW

**Comment by baitun** [comment]
Try to resolve conflict by yourself.
```bash
git checkout task-18
git merge master
# ... there will be conflicts, resolve it
git push
```

**Comment by rudensergey** [comment]
> Try to resolve conflict by yourself.
> 
> ```shell
> git checkout task-18
> git merge master
> # ... there will be conflicts, resolve it
> git push
> ```

@baitun Done!) remove all DS-files from repo

**Comment by rudensergey** [comment]
> > Try to resolve conflict by yourself.
> > ```shell
> > git checkout task-18
> > git merge master
> > # ... there will be conflicts, resolve it
> > git push
> > ```
> 
> @baitun Done!) remove all DS-files from repo

**Comment by baitun** [comment]
Very good!

**Pull request closed without merging**
